language: python

python:
  - "3.6"
  - "3.7"

script:
  - py.test app_test.py


# https://www.smartfile.com/blog/testing-python-with-travis-ci/
# https://docs.travis-ci.com/user/docker/#using-docker-compose
