version: '3.5'
# version of docker-compose that we are using
services:
# containters we want to run
  database:
    container_name: postgres
    # provides an instance of postgress database
    image: postgres:latest
    env_file: database.conf
    # dotenv file
    volumes:
    - db_volume:/var/lib/postgresql
    # Inside the container, this directory is where Postgres stores all the relevant tables and databases.
    # We are defining a volume inside the compose file and mounting it at this mount point.
    ports:
      - 127.0.0.1:5000:5432
    # host machine:dbcontainer ports 
    # map ports from the host machine to the container
    # incoming requests at docker host port 5002 will be forwarded to the port 5432 of 
    # the database container, where Postgres server can process it.

volumes:
  # For data persistence purposes, we are storing data in a mouted volume which we have named db-data
  db_volume:

  # database with docker-compose learned here: https://linuxhint.com/run_postgresql_docker_compose/
  # and here: https://medium.com/@audretschjames/understanding-docker-as-if-it-were-a-gameboy-96c96392efbf

